// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const list: string;
export const project: string;
export const infos: string;
export const pictures: string;
export const picture: string;
export const copyright: string;
export const link: string;
export const url: string;
