// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const hero: string;
export const intro: string;
export const disponibility: string;
export const indicator: string;
export const glowingIndicator: string;
export const scrolldown: string;
